name: webapp
services:
    web:
        build: ./frontend
        ports:
            - 3000:3000
    api:
        build: ./backend
        ports:
            - 3001:3001
        environment: 
            DB_URL:  mongodb://db/webapp
    db:
        image: mongo:4.0-xenial
        ports:
            - 271017:27017
        volumes:
            - webapp:/data/db
volumes:
    webapp:
