name: webapp
services:
    web:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        image: webapp-web:1
        ports:
            - 80:80
        restart: unless-stopped
    api:
        build: ./backend
        image: webapp-api:1
        ports:
            - 3001:3001
        environment: 
            DB_URL:  mongodb://db/webapp
        command: ./docker-entrypoint.sh
        restart: unless-stopped
    db:
        image: mongo:4.0-xenial
        ports:
            - 27017:27017
        volumes:
            - webapp:/data/db
        restart: unless-stopped
    
volumes:
    webapp:
