name: webapp
services:
    web:
        build: ./frontend
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app
    web-test:
        image: webapp-web
        volumes:
            - ./frontend:/app
        command: npm test
    api:
        build: ./backend
        ports:
            - 3001:3001
        environment: 
            DB_URL:  mongodb://db/webapp
        volumes:
            - ./backend:/app
        command: ./docker-entrypoint.sh
    db:
        image: mongo:4.0-xenial
        ports:
            - 27017:27017
        volumes:
            - webapp:/data/db
    
volumes:
    webapp:
